# Generated by Django 5.2.1 on 2025-05-31 21:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='issue_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='period_end',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('contract', 'period_start', 'period_end')},
        ),
    ]
