# Generated by Django 5.2.1 on 2025-06-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_unique_active_contract_per_client_and_more'),
        ('invoices', '0004_invoice_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='period_end',
            new_name='expiration_date',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('contract', 'created_at', 'expiration_date')},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='period_start',
        ),
    ]
