# Generated by Django 5.2.1 on 2025-06-01 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_unique_active_contract_per_client_and_more'),
        ('invoices', '0005_rename_period_end_invoice_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='contracts.contract'),
        ),
    ]
