# Generated by Django 5.2.1 on 2025-06-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_rename_expiration_date_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(null=True),
        ),
    ]
