# Generated by Django 5.2.1 on 2025-06-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_period_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
