# Generated by Django 5.2.1 on 2025-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0002_alter_contract_client_alter_contract_vehicle'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('client',), name='unique_active_contract_per_client'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('vehicle',), name='unique_active_contract_per_vehicle'),
        ),
    ]
