# Generated by Django 5.2.1 on 2025-06-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_unique_active_contract_per_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
    ]
