# Generated by Django 5.2.1 on 2025-06-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_unique_active_contract_per_client_and_more'),
        ('invoices', '0006_alter_invoice_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='expiration_date',
            new_name='due_date',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('contract', 'created_at', 'due_date')},
        ),
    ]
