# Generated by Django 5.2.1 on 2025-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
    ]
